name: Deploy to GCloud Compute Enginge VM

on:
  push:
    branches:
      - triggers

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 'Build Environment'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository - ${{ secrets.GCLOUD_PROJECT_ID }}
        uses: actions/checkout@v4

      - name: Install PHP Dependencies
        uses: php-actions/composer@v6
        with:
          dev: no
          args: --profile --ignore-platform-reqs

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '>=20.11.0'

      - name: Install Node Depend
        run: |
          npm install
          npm install -D @types/ziggy-js

      - name: Make Frontend Build
        run: npm run build

      - name: 'Google Cloud Authentication With Service Account Key JSON'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}

      # - name: 'Check GCLOUD CLI'
      #   run: 'gcloud info'

      - name: SCP COMPOSER VENDOR FILES
        run: |
          gcloud compute scp --project=$GCLOUD_PROJECT_ID --zone=$GCLOUD_ZONE --recurse node_modules  $GCLOUD_VM_INSTANCE:scp
          gcloud compute scp --project=$GCLOUD_PROJECT_ID --zone=$GCLOUD_ZONE --recurse public/build  $GCLOUD_VM_INSTANCE:scp
          gcloud compute scp --project=$GCLOUD_PROJECT_ID --zone=$GCLOUD_ZONE --recurse vendor  $GCLOUD_VM_INSTANCE:scp
          gcloud compute scp --project=$GCLOUD_PROJECT_ID --zone=$GCLOUD_ZONE composer.json  $GCLOUD_VM_INSTANCE:scp
          gcloud compute scp --project=$GCLOUD_PROJECT_ID --zone=$GCLOUD_ZONE composer.lock  $GCLOUD_VM_INSTANCE:scp
          gcloud compute scp --project=$GCLOUD_PROJECT_ID --zone=$GCLOUD_ZONE package-lock.json  $GCLOUD_VM_INSTANCE:scp
          gcloud compute scp --project=$GCLOUD_PROJECT_ID --zone=$GCLOUD_ZONE package.json  $GCLOUD_VM_INSTANCE:scp
        env:
          GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
          GCLOUD_ZONE: ${{ secrets.GCLOUD_ZONE }}
          GCLOUD_VM_INSTANCE: ${{ secrets.GCLOUD_VM_INSTANCE }}
          GCLOUD_SERVICE_ACCOUNT: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_EMAIL }}

      # - name: SSH and deploy
      #   run: |
      #     gcloud compute ssh --project=$GCLOUD_PROJECT_ID --zone=$GCLOUD_ZONE $GCLOUD_VM_INSTANCE --command="
      #     cd /var/opt/laracar.sushmaregan.com/ &&
      #     sudo git pull &&
      #     npm install &&
      #     npm run build
      #     "
      #   env:
      #     GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
      #     GCLOUD_ZONE: ${{ secrets.GCLOUD_ZONE }}
      #     GCLOUD_VM_INSTANCE: ${{ secrets.GCLOUD_VM_INSTANCE }}
      #     GCLOUD_SERVICE_ACCOUNT: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_EMAIL }}
